// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CloseWindow():Promise<void>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateDir(arg1:string):Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAutoSyncStatus():Promise<app.GetAutoSyncStatusRes>;

export function GetConfig(arg1:string):Promise<string>;

export function GetGitRepoInfo(arg1:app.GetGitRepoInfoReq):Promise<app.GetGitRepoInfoRes>;

export function GetJsonConfig(arg1:string,arg2:any):Promise<void>;

export function GetSyncLogs(arg1:app.GetSyncLogsReq):Promise<app.GetSyncLogsRes>;

export function GetSystemEnv(arg1:string):Promise<string>;

export function GetTempDir():Promise<string>;

export function GetWindowState():Promise<app.WindowState>;

export function GitSync(arg1:app.GitSyncReq):Promise<app.GitSyncRes>;

export function HideWindow():Promise<void>;

export function InitSettingsDb():Promise<void>;

export function IsWindowMaximized():Promise<boolean>;

export function ListDir(arg1:string):Promise<Array<string>>;

export function LoadGitRepoList():Promise<app.GitRepoListRes>;

export function MaximizeWindow():Promise<void>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenUrl(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function ReadEnvFiles(arg1:string):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveGitRepoList(arg1:app.GitRepoListReq):Promise<app.GitRepoListRes>;

export function SaveWindowState(arg1:app.WindowState):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendToFrontend(arg1:string,arg2:any):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetJsonConfig(arg1:string,arg2:any):Promise<void>;

export function SetSystemEnv(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAutoSync(arg1:app.StartAutoSyncReq):Promise<app.StartAutoSyncRes>;

export function StartLocalFileServer(arg1:number):Promise<void>;

export function StopAutoSync():Promise<void>;

export function UnmaximizeWindow():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
