// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['app']['App']['CloseWindow']();
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['app']['App']['ConfirmDialog'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['app']['App']['CopyToClipboard'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['app']['App']['CreateDir'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['app']['App']['DeleteConfig'](arg1);
}

export function FileExists(arg1) {
  return window['go']['app']['App']['FileExists'](arg1);
}

export function GetAutoSyncStatus() {
  return window['go']['app']['App']['GetAutoSyncStatus']();
}

export function GetConfig(arg1) {
  return window['go']['app']['App']['GetConfig'](arg1);
}

export function GetGitRepoInfo(arg1) {
  return window['go']['app']['App']['GetGitRepoInfo'](arg1);
}

export function GetJsonConfig(arg1, arg2) {
  return window['go']['app']['App']['GetJsonConfig'](arg1, arg2);
}

export function GetSyncLogs(arg1) {
  return window['go']['app']['App']['GetSyncLogs'](arg1);
}

export function GetSystemEnv(arg1) {
  return window['go']['app']['App']['GetSystemEnv'](arg1);
}

export function GetTempDir() {
  return window['go']['app']['App']['GetTempDir']();
}

export function GetWindowState() {
  return window['go']['app']['App']['GetWindowState']();
}

export function GitSync(arg1) {
  return window['go']['app']['App']['GitSync'](arg1);
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function InitSettingsDb() {
  return window['go']['app']['App']['InitSettingsDb']();
}

export function IsWindowMaximized() {
  return window['go']['app']['App']['IsWindowMaximized']();
}

export function ListDir(arg1) {
  return window['go']['app']['App']['ListDir'](arg1);
}

export function LoadGitRepoList() {
  return window['go']['app']['App']['LoadGitRepoList']();
}

export function MaximizeWindow() {
  return window['go']['app']['App']['MaximizeWindow']();
}

export function MessageDialog(arg1, arg2) {
  return window['go']['app']['App']['MessageDialog'](arg1, arg2);
}

export function MinimizeWindow() {
  return window['go']['app']['App']['MinimizeWindow']();
}

export function OpenUrl(arg1) {
  return window['go']['app']['App']['OpenUrl'](arg1);
}

export function PathExists(arg1) {
  return window['go']['app']['App']['PathExists'](arg1);
}

export function ReadEnvFiles(arg1) {
  return window['go']['app']['App']['ReadEnvFiles'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function SaveGitRepoList(arg1) {
  return window['go']['app']['App']['SaveGitRepoList'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['app']['App']['SaveWindowState'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SendToFrontend(arg1, arg2) {
  return window['go']['app']['App']['SendToFrontend'](arg1, arg2);
}

export function SetConfig(arg1, arg2) {
  return window['go']['app']['App']['SetConfig'](arg1, arg2);
}

export function SetJsonConfig(arg1, arg2) {
  return window['go']['app']['App']['SetJsonConfig'](arg1, arg2);
}

export function SetSystemEnv(arg1, arg2) {
  return window['go']['app']['App']['SetSystemEnv'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartAutoSync(arg1) {
  return window['go']['app']['App']['StartAutoSync'](arg1);
}

export function StartLocalFileServer(arg1) {
  return window['go']['app']['App']['StartLocalFileServer'](arg1);
}

export function StopAutoSync() {
  return window['go']['app']['App']['StopAutoSync']();
}

export function UnmaximizeWindow() {
  return window['go']['app']['App']['UnmaximizeWindow']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['app']['App']['WriteFile'](arg1, arg2);
}
